name: Build Minecraft Webcam

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Build server plugin
      working-directory: server
      run: ./gradlew build
    - name: Build client mod
      working-directory: client
      run: ./gradlew build
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          server/build/libs/*.jar
          client/build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
